#! /Users/salman/.rbenv/shims/ruby 

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class Problem2
  # find sum of even valued fibonacci numbers below n
    def custom_sum n
      fib_array = [1,2]
      for i in (2..n-1)
        next_term =  fib_array[i-1] + fib_array[i-2]
	break if (next_term >= 4000000)
	fib_array << next_term  
      end
      fib_array.inject(0) { |sum,x| x%2==0 ? sum+x : sum }
    end
end

object = Problem2.new
puts object.custom_sum 10
puts object.custom_sum 4000000
